name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - abseil-cpp=20200225.2
  - aiohttp=3.6.3
  - argon2-cffi=20.1.0
  - arrow-cpp=0.15.1
  - arviz=0.10.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.2.0
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.70
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.2.1
  - boost-cpp=1.67.0
  - boto=2.49.0
  - boto3=1.15.16
  - botocore=1.18.16
  - branca=0.4.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bz2file=0.98
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.3
  - cftime=1.2.1
  - chardet=3.0.4
  - clang=11.0.0
  - clang-11=11.0.0
  - clangxx=11.0.0
  - click=7.1.2
  - colorama=0.4.3
  - compiler-rt=11.0.0
  - compiler-rt_win-64=11.0.0
  - convertdate=2.2.2
  - cryptography=3.1.1
  - curl=7.71.1
  - cvxpy=1.1.6
  - cvxpy-base=1.1.6
  - cycler=0.10.0
  - cython=0.29.21
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.15.2
  - double-conversion=3.1.5
  - ecos=2.0.7.post1
  - entrypoints=0.3
  - ephem=3.7.7.1
  - et_xmlfile=1.0.1
  - fbprophet=0.7.1
  - folium=0.11.0
  - freetype=2.10.3
  - future=0.18.2
  - gensim=3.8.3
  - gflags=2.2.2
  - glog=0.4.0
  - google-api-core=1.22.2
  - google-auth=1.22.0
  - google-cloud-core=1.4.3
  - google-cloud-storage=1.31.2
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - grpc-cpp=1.26.0
  - grpcio=1.31.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - holidays=0.10.3
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imbalanced-learn=0.7.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jdcal=1.4.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.2.0
  - korean_lunar_calendar=0.2.1
  - krb5=1.18.2
  - lcms2=2.11
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libiconv=1.16
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libpython=2.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lunarcalendar=0.0.9
  - lxml=4.6.1
  - lz4-c=1.8.1.2
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.4.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - multidict=4.7.5
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.1
  - netcdf4=1.5.4
  - networkx=2.5
  - nltk=3.5
  - notebook=6.1.4
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - osqp=0.6.1
  - packaging=20.4
  - pandas=1.1.3
  - pandasql=0.7.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.3
  - plotly=4.11.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.11.2
  - ptyprocess=0.6.0
  - py4j=0.10.9
  - pyarrow=0.15.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.1
  - pymeeus=0.3.7
  - pymongo=3.11.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pyspark=3.0.0
  - pystan=2.19.1.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - re2=2019.08.01
  - regex=2020.10.15
  - requests=2.24.0
  - retrying=1.3.3
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - scikit-surprise=1.1.1
  - scipy=1.5.0
  - scs=2.1.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - setuptools-git=1.2
  - simplegeneric=0.8.1
  - sip=4.19.13
  - six=1.15.0
  - smart_open=3.0.0
  - snappy=1.1.8
  - soupsieve=2.0.1
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift-cpp=0.11.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.5
  - uriparser=0.9.3
  - urllib3=1.25.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.16.1
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.3.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - gast==0.3.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - h5py==2.10.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.3.2
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - orc==0.1.0
    - pybind11==2.5.0
    - requests-oauthlib==1.3.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xgboost==1.2.1
    - yarl==1.5.1
